### ISSUE TITLE
Allow options to be passed to plugins from config YAML

### ISSUE THREAD

**Issue by n7st** [n7st/Metal#7]
```yaml
plugins:
  - path: "/path/to/plugin.so"
    options:
      api_key: "api-key-here"
```
